modLoader = "javafml"
loaderVersion = "[2,)"

license = "${modLicense}"
issueTrackerURL = "https://github.com/cschierig/Privileged/issues"
showAsResourcePack = false

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${author}"
logoFile = "assets/${modId}/icon.png"
description = "${modDescription}"

[[mixins]]
config = "${modId}.mixins.json"
